version: '3.3'

services:
  server1:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=3000
    networks:
      - loadBalancer

  server2:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    networks:
      - loadBalancer

  server3:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=3002
    networks:
      - loadBalancer

  # agent:
  #   build:
  #     context: ../../TT_neuro
  #     dockerfile: Dockerfile
  #   environment:
  #     - PORT=5555
  #   networks:
  #     - loadBalancer

  nginx:
    build:
      context: ../../TT_module
      dockerfile: Dockerfile
    # image: nginx:alpine
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    networks:
      - loadBalancer
    depends_on:
      - server1
      - server2
      - server3
      # - agent

networks:
  loadBalancer:
    driver: bridge
